create table cs_users (
  id bigint generated by default as identity primary key,
  openim_user_id varchar(128) not null,
  display_name varchar(255),
  joined_demo_group_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_cs_users_openim_user_id unique (openim_user_id)
);

create table abuse_subjects (
  id bigint generated by default as identity primary key,
  subject_type varchar(32) not null,
  subject_value_hash varchar(128) not null,
  status varchar(32) not null,
  reason text,
  expires_at timestamptz,
  created_by varchar(128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_abuse_subjects_subject_type check (
    subject_type in ('ip', 'ip_cidr', 'email', 'phone', 'openim_user_id', 'device_fingerprint')
  ),
  constraint ck_abuse_subjects_status check (
    status in ('blocked', 'watch', 'allowlisted')
  ),
  constraint uq_abuse_subjects_subject unique (subject_type, subject_value_hash)
);

create table verification_events (
  id bigint generated by default as identity primary key,
  channel varchar(16) not null,
  target_hash varchar(128) not null,
  ip_hash varchar(128),
  ip_cidr_hash varchar(128),
  device_fingerprint_hash varchar(128),
  openim_user_id varchar(128),
  action varchar(32) not null,
  decision varchar(32) not null,
  reason text,
  provider_request_id varchar(128),
  created_at timestamptz not null default now(),
  constraint ck_verification_events_channel check (channel in ('sms', 'smtp')),
  constraint ck_verification_events_action check (action in ('send_code', 'verify_code')),
  constraint ck_verification_events_decision check (
    decision in ('allowed', 'blocked', 'challenged', 'provider_failed')
  )
);

create table registration_events (
  id bigint generated by default as identity primary key,
  openim_user_id varchar(128),
  email_hash varchar(128),
  phone_hash varchar(128),
  ip_hash varchar(128),
  ip_cidr_hash varchar(128),
  device_fingerprint_hash varchar(128),
  decision varchar(32) not null,
  reason text,
  created_at timestamptz not null default now(),
  constraint ck_registration_events_decision check (decision in ('allowed', 'blocked', 'failed'))
);

create table raw_messages (
  id bigint generated by default as identity primary key,
  message_id varchar(128) not null,
  group_id varchar(128) not null,
  openim_user_id varchar(128) not null,
  sender_name varchar(255),
  sent_at timestamptz not null,
  content_text text,
  message_type varchar(64),
  mentions_json jsonb not null default '[]'::jsonb,
  reply_to_message_id varchar(128),
  is_from_bot boolean not null default false,
  visible_to_user_ids_json jsonb not null default '[]'::jsonb,
  raw_payload jsonb not null,
  created_at timestamptz not null default now(),
  constraint uq_raw_messages_message_id unique (message_id)
);

create table ai_quota_accounts (
  id bigint generated by default as identity primary key,
  openim_user_id varchar(128) not null,
  quota_date date not null,
  daily_limit integer not null,
  bonus_amount integer not null default 0,
  used_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_ai_quota_accounts_daily_limit check (daily_limit >= 0),
  constraint ck_ai_quota_accounts_bonus_amount check (bonus_amount >= 0),
  constraint ck_ai_quota_accounts_used_count check (used_count >= 0),
  constraint ck_ai_quota_accounts_balance check (used_count <= daily_limit + bonus_amount),
  constraint uq_ai_quota_accounts_user_date unique (openim_user_id, quota_date)
);

create table ai_quota_ledger (
  id bigint generated by default as identity primary key,
  openim_user_id varchar(128) not null,
  quota_date date not null,
  event_type varchar(32) not null,
  delta integer not null,
  balance_after integer not null,
  reason text,
  operator_id varchar(128),
  request_id varchar(128),
  created_at timestamptz not null default now(),
  constraint ck_ai_quota_ledger_event_type check (
    event_type in ('consume', 'admin_add', 'admin_set', 'refund')
  ),
  constraint ck_ai_quota_ledger_balance_after check (balance_after >= 0)
);

create table bot_interactions (
  id bigint generated by default as identity primary key,
  trigger_message_id varchar(128) not null,
  openim_user_id varchar(128) not null,
  group_id varchar(128) not null,
  user_question text,
  intent_type varchar(32) not null,
  quota_ledger_id bigint references ai_quota_ledger (id),
  context_window_start timestamptz,
  context_window_end timestamptz,
  used_mini_summary_ids jsonb not null default '[]'::jsonb,
  used_raw_message_ids jsonb not null default '[]'::jsonb,
  bot_answer text,
  response_message_id varchar(128),
  visibility varchar(32),
  visible_to_user_ids_json jsonb not null default '[]'::jsonb,
  status varchar(32) not null,
  model_name varchar(128),
  model_latency_ms integer,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_bot_interactions_intent_type check (intent_type in ('chat', 'pull_archive')),
  constraint ck_bot_interactions_status check (status in ('pending', 'succeeded', 'failed', 'quota_denied')),
  constraint ck_bot_interactions_model_latency_ms check (model_latency_ms is null or model_latency_ms >= 0),
  constraint uq_bot_interactions_trigger_intent unique (trigger_message_id, intent_type)
);

create table mini_summaries (
  id bigint generated by default as identity primary key,
  group_id varchar(128) not null,
  window_start timestamptz not null,
  window_end timestamptz not null,
  message_count integer not null default 0,
  participant_count integer not null default 0,
  participants_json jsonb not null default '[]'::jsonb,
  summary_text text,
  topics_json jsonb not null default '[]'::jsonb,
  status varchar(32) not null,
  model_name varchar(128),
  model_latency_ms integer,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_mini_summaries_window check (window_end > window_start),
  constraint ck_mini_summaries_message_count check (message_count >= 0),
  constraint ck_mini_summaries_participant_count check (participant_count >= 0),
  constraint ck_mini_summaries_status check (status in ('pending', 'succeeded', 'failed')),
  constraint ck_mini_summaries_model_latency_ms check (model_latency_ms is null or model_latency_ms >= 0),
  constraint uq_mini_summaries_window unique (group_id, window_start, window_end)
);

create table archive_summaries (
  id bigint generated by default as identity primary key,
  group_id varchar(128) not null,
  window_start timestamptz not null,
  window_end timestamptz not null,
  online_count integer not null default 0,
  mini_summary_ids jsonb not null default '[]'::jsonb,
  topics_json jsonb not null default '[]'::jsonb,
  summary_text text,
  public_push_message_id varchar(128),
  status varchar(32) not null,
  model_name varchar(128),
  model_latency_ms integer,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_archive_summaries_window check (window_end > window_start),
  constraint ck_archive_summaries_online_count check (online_count >= 0),
  constraint ck_archive_summaries_status check (status in ('pending', 'succeeded', 'failed')),
  constraint ck_archive_summaries_model_latency_ms check (model_latency_ms is null or model_latency_ms >= 0),
  constraint uq_archive_summaries_window unique (group_id, window_start, window_end)
);

create unique index uq_ai_quota_ledger_request_id
  on ai_quota_ledger (request_id)
  where request_id is not null;

create index idx_cs_users_joined_demo_group_at on cs_users (joined_demo_group_at);

create index idx_abuse_subjects_status_expires_at on abuse_subjects (status, expires_at);
create index idx_abuse_subjects_updated_at on abuse_subjects (updated_at);

create index idx_verification_events_target_created_at on verification_events (target_hash, created_at desc);
create index idx_verification_events_ip_created_at on verification_events (ip_hash, created_at desc);
create index idx_verification_events_openim_user_created_at on verification_events (openim_user_id, created_at desc);
create index idx_verification_events_decision_created_at on verification_events (decision, created_at desc);

create index idx_registration_events_openim_user_created_at on registration_events (openim_user_id, created_at desc);
create index idx_registration_events_ip_created_at on registration_events (ip_hash, created_at desc);
create index idx_registration_events_email_created_at on registration_events (email_hash, created_at desc);
create index idx_registration_events_phone_created_at on registration_events (phone_hash, created_at desc);
create index idx_registration_events_decision_created_at on registration_events (decision, created_at desc);

create index idx_raw_messages_group_sent_at on raw_messages (group_id, sent_at);
create index idx_raw_messages_openim_user_sent_at on raw_messages (openim_user_id, sent_at);
create index idx_raw_messages_reply_to_message_id on raw_messages (reply_to_message_id);
create index idx_raw_messages_is_from_bot_created_at on raw_messages (is_from_bot, created_at);

create index idx_ai_quota_ledger_user_date_created_at on ai_quota_ledger (openim_user_id, quota_date, created_at desc);
create index idx_ai_quota_ledger_event_type_created_at on ai_quota_ledger (event_type, created_at desc);

create index idx_bot_interactions_user_created_at on bot_interactions (openim_user_id, created_at desc);
create index idx_bot_interactions_group_created_at on bot_interactions (group_id, created_at desc);
create index idx_bot_interactions_status_created_at on bot_interactions (status, created_at desc);
create index idx_bot_interactions_quota_ledger_id on bot_interactions (quota_ledger_id);

create index idx_mini_summaries_group_window_start on mini_summaries (group_id, window_start);
create index idx_mini_summaries_status_updated_at on mini_summaries (status, updated_at);

create index idx_archive_summaries_group_window_start on archive_summaries (group_id, window_start);
create index idx_archive_summaries_status_updated_at on archive_summaries (status, updated_at);
